name: Create new nix-index

on:
  workflow_dispatch:

jobs:
  create-index:
    name: Create index for each system
    runs-on: ubuntu-latest
    strategy:
      matrix:
        system: ['x86_64-linux']
    env:
      SYSTEM: ${{ matrix.system }}
    steps:
     - uses: cachix/install-nix-action@v31
     - name: Generate index
       run: |
         nix profile install github:player131007/nix-index github:nixos/nixpkgs/nixos-unstable#cargo-flamegraph
         flamegraph -o graph.svg -- nix-index --path-cache --filter-prefix 67 --compression 0 2>/dev/null
     - uses: actions/upload-artifact@v4
       with:
         path: graph.svg
